### ISSUE TITLE
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command

### ISSUE THREAD

**Issue by xov17** [DonJayamanne/vscodeJupyter#34] opened 2017-04-01 18:20 UTC
### Environment data
VS Code version: Version 1.10.2 (1.10.2)
Jupyter Extension version: 1.0.0 
OS and version: macOS Sierra 10.12.3

### Logs
Output from ```Jupyter``` output panel
```
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
Notebook not selected/started
```
Output from ```Console window``` (Help->Developer Tools menu)
```
workbench.main.js:142 spawn jupyter ENOENT: Error: spawn jupyter ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ workbench.main.js:142
workbench.main.js:103 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' commande.doShow @ workbench.main.js:103
workbench.main.js:136 [Extension Host] rejected promise not handled within 1 second
workbench.main.js:142 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' commande.onUnexpectedError @ workbench.main.js:142
```

### Actual behavior
Tried to run this code and clicked on "Run Cell"
#%%
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show() 

Says to "Select Notebook". Tried to Select Notebook, but was unable to. So I tried to Start a New Notebook, but still got an error.

### Expected  behavior
To run the sample code.

### Steps to reproduce:
- I was using a virtualenv, so I opened VS Code from the terminal as I always do with the virtualenv where Jupyter notebook is installed.
- I created a test.py file, pasted the sample code. Clicked "Run Cell". Got the above results.
- Then I realized that I didn't paste the configuration settings (as I found them on the docs of the Python VS Code extension that you also made), so I did. But I still get errors. The above errors are what I get after I pasted the configs.
- Configs I put on settings.json:
     "python.jupyter.defaultKernel": "",
     "python.jupyter.startupCode": [
         "%matplotlib inline"
     ],
     "python.jupyter.appendResults": true,
- Then I also tried opening the virtualenv from VS Code's inbuilt command line, just to see if it would help. Still same error.

**Comment by quanvuong** [comment] 2017-04-07 10:59
I had the same error. Turns out I didn't install jupyter yet. Even after I installed, I have to included the path to the jupyter executable before it works. Hope this helps!

**Comment by jsinglet** [comment] 2017-04-07 18:05
I'm having exactly this error. I've tried running code directly from a shell (where I am certain that jupyter is installed) as well as running it after selecting my workspace interpreter. Ideas?

**Comment by quanvuong** [comment] 2017-04-07 21:17
Did you have the correct path to a bin folder that contains the jupyter executable ? For me, the jupyter executable was in my python 3.6 folder. It was confusing because I have python 2.7, 3.5 and 3.6 on a single computer.

**Comment by jsinglet** [comment] 2017-04-07 21:31
@quanvuong - I am using conda so it's at: 

```shell
which jupyter
/Users/me/Applications/conda/envs/strongarm/bin/jupyter
```

**Comment by quanvuong** [comment] 2017-04-07 21:36
If you go into `/Users/me/Applications/conda/envs/strongarm/bin/` and run `./jupyter notebook`. Does it work ?

**Comment by jsinglet** [comment] 2017-04-07 22:01
Yes, it starts it right up. Also, I can do it without going into that directory (since it's on my PATH).

**Comment by quanvuong** [comment] 2017-04-07 22:03
mhm out of idea here. sorry.

**Comment by jsinglet** [comment] 2017-04-07 22:05
is it possible this has to do with the new API tokens? I notice now I need to pass a token to connect to the notebook...

**Comment by jsinglet** [comment] 2017-04-07 22:06
Right now all I can do to use this extension is to "connect to remote notebook" and give it the address, port, and token of a instance I start on the command line.

**Comment by DonJayamanne** [comment] 2017-04-08 03:23
Hi guys, I will be looking into this some time later today, or tomorrow. It is Saturday here. Apologies for this. I will need your assistance to resolve this. I believe the issue is with the location of Jupyter not being detected... Any ways, let me analyse this in detail

**Comment by jsinglet** [comment] 2017-04-08 03:40
Sure thing. Let me know how I can help.

**Comment by xov17** [comment] 2017-04-08 11:31
Hi, yeah I believe it's about the location of Jupyter not being detected. I'm quite confused about this since I start VS code from command line always, with the virtualenv already loaded. And the other VS code extensions, like the Python extension, finds my installed packages for autocomplete, etc. So am not sure what's happening.

**Comment by DonJayamanne** [comment] 2017-04-08 13:32
The following changeset will fix the issue. 
https://github.com/DonJayamanne/vscodeJupyter/commit/c08aa90a1a8462757371c82c39687a77c1afcff0

The problem is as most have identified, its to do with the path. When running Jupyter I'm not considering the path of python being used. 
One last thing, you will need the Python extension installed (this is so that you can configure the path to Python). 

If you're wondering why separate the two extensions if this depends on the other, simple - maintenance.

**Comment by DonJayamanne** [comment] 2017-04-08 13:33
Personal notes:  
Remaining fixes - update documentation to mention the dependency on the Python extension.  
Add code to check if the python extension is installed.

**Comment by DonJayamanne** [comment] 2017-04-08 13:34
Will publish something soon guys. Once again apologies for this issue & the rest. Hopefully I can get these major issues sorted by next week and focus on some enhancements (viewing dataframes, etc).

Will let you know when I publish a new version

**Comment by jsinglet** [comment] 2017-04-08 18:10
Great. Looking forward to being able to use new dataframe features.

**Comment by xov17** [comment] 2017-04-16 10:48
Thank you @DonJayamanne ! I'm wondering, would it be possible to use the extension without specifying the python paths in settings.json with the Python extension? The Python extension sees my python paths when I open VS code from command line with the virtualenv loaded. Would it behave the same way?

**Comment by xov17** [comment] 2017-04-16 10:57
I'm not sure why.. But the extension is still not working with me?

I get this error:
Unable to determine version of Jupyter, Error: spawn jupyter ENOENT
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command

This was when I loaded VS code with virtualenv on from terminal. But after it didn't work, I then specified my python paths as so:
       "python.pythonPath": "~/virtualenvs/cv/bin/python",
          "python.autoComplete.extraPaths": [
              "~/virtualenvs/cv/lib/python2.7",
              "~/virtualenvs/cv/lib/python2.7/site-packages",
              "/usr/lib/python2.7",
              "/usr/lib/python2.7/site-packages"],

They're what I were using before I started just opening VS Code from terminal.

**Comment by DonJayamanne** [comment] 2017-04-16 11:10
Please upload the contents of your workspace settings.json

**Comment by DonJayamanne** [comment] 2017-04-16 11:11
Fyi, please try to specify the path using the command 'Selwct workspace interpreter'

**Comment by xov17** [comment] 2017-04-16 13:12
I looked at the Jupyter output log and found this:
[I 21:07:02.030 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=8cf77fc4e7a5c54c74668f1fafdb4ff81920da0d3110f907
[I 21:07:02.030 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:07:02.031 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=8cf77fc4e7a5c54c74668f1fafdb4ff81920da0d3110f907
[I 21:07:07.445 NotebookApp] Kernel started: 566fd0bb-4d7b-435d-a7c5-794da894c0de
/Users/agatha/virtualenvs/cv/bin/python2.7: No module named ipykernel_launcher
[I 21:07:10.442 NotebookApp] KernelRestarter: restarting kernel (1/5)

I updated workspace settings with settings.json (for the first time actually, I was using the Python extension for autocomplete and pep8 before without specifying paths there) and here's what I put:
     "python.pythonPath": "/Users/agatha/virtualenvs/cv/bin/python",
     "python.autoComplete.extraPaths": [
         "/Users/agatha/virtualenvs/cv/lib/python2.7",
         "/Users/agatha/virtualenvs/cv/lib/python2.7/site-packages"
     ],



     "python.linting.pep8Enabled": true,
     
          "python.jupyter.defaultKernel": "",
          "python.jupyter.startupCode": [
              "%matplotlib inline"
          ],
          "python.jupyter.appendResults": true,
     

Somehow I think the extension is having problems with still finding the jupyter extension. I just tried installing the extension globally, and it worked. Albeit not finding matplotlib and numpy as it's in my virtualenv.

**Comment by jsinglet** [comment] 2017-04-16 18:21
Writing to confirm the fix worked for me in version 1.1.1.

**Comment by puma007** [comment] 2017-04-21 03:19
@DonJayamanne ,I have the same error after I install version 1.1.1.
Operating system : win10 64bit
Python version : 3.5
Vs Code version : 1.11.2
jupyter version : 1.1.1

When I click "run cell" link in vs code,it  prompts “start a new notebook or select an existing notebook”. If i click the "start a new notebook" link,the Cpu occupancy rate will reach 99%, and start a lot of python threads! 
The Jupyter output log:
`[I 11:05:23.941 NotebookApp] Serving notebooks from local directory: C:\Users\foxhu
[I 11:05:23.941 NotebookApp] 0 active kernels
[I 11:05:23.943 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=8f45800eda24929b76e3b13f3c3539becfeff9ce70fdcee2
[I 11:05:23.944 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:05:23.962 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=8f45800eda24929b76e3b13f3c3539becfeff9ce70fdcee2`

settings.json:
`"python.pythonPath": "C:/Programs/Python/Python35/python",
    "python.autoComplete.extraPaths": ["C:/Programs/Python/Python35/Lib/site-packages"],
    "python.jupyter.defaultKernel": "",
    "python.jupyter.startupCode": [
        "%matplotlib inline"
    ],
    "python.jupyter.appendResults": true`

**Comment by circlecrystal** [comment] 2017-08-19 02:27
Same issue.

Just installed Jupyter in vscode for the first time. Tried to run a hello world, but failed.

Error:
Unable to determine version of Jupyter, Error: spawn jupyter ENOENT
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command

This is my workspace interpreter setting:
"python.pythonPath": "~/virtual_environment/bin/python3",

**Comment by DonJayamanne** [comment] 2017-08-19 04:12
Do you have the Jupyter environment set up? Do you have anaconda or similar installed?

**Comment by DonJayamanne** [comment] 2017-08-19 04:18
Phase check the following:
https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-(IPython)-Prerequisites

**Comment by circlecrystal** [comment] 2017-08-19 09:20
Yes, I have installed all the prerequisites.

BTW, I tried running Jupyter in browser, it`s all fine. Just vscode jupyter extension doesn`t work.

**Comment by circlecrystal** [comment] 2017-08-19 15:00
UPDATE:

After some further tests, I have found:

1. 'Enter the url of local/remote Jupyter notebook' is currently the only working solution to use Jupyter in vscode
2. Neither 'Select an existing notebook' nor 'start a new notebook' works.

![screen_record](https://user-images.githubusercontent.com/5665980/29487817-1b910562-8532-11e7-8f8f-3588f8b031b3.gif)

**Comment by jsinglet** [comment] 2017-08-19 17:21
By the way I constantly have this problem. It seems like it would be helpful if the process for firing up a new notebook was more transparent.

**Comment by boazdori** [comment] 2017-08-30 13:58
win 10
anaconda3
python 3.6.1
jupyter 1.0.0
VS Code version: Version 1.15.1
same as above jupyter notebook not working in vs code

**Comment by rgrinberg** [comment] 2017-08-31 23:27
I also get this problem on anaconda/python3/ on Linux

**Comment by GintMist** [comment] 2017-09-07 10:51
In my setup(Arch Linux, VS Code from AUR) if Anaconda added path via editing ~/.bashrc and VS Code started on GUI, vscodejupyter throws error like this issue. To prevent error I need to add  Anaconda to ~/.bash_profile or start VS Code from terminal with "code" command. Maybe this can be a general problem, I am not sure. Just FYI.

**Comment by saurabhwahile** [comment] 2017-09-10 17:30
A possible suspected code is jupyterServices/notebook/factory.js line 51:
`procUtils_1.spanwPythonFile('jupyter', ['notebook'].concat(args), startupFolder)`

As per my belief, it tries to start jupyter from the PYTHONPATH, so if you have a distribution like anaconda which has jupyter preinstalled, and you are using a virtualenv or conda environment, make sure, that jupyter is installed in the environment.

**Comment by jsinglet** [comment] 2017-09-12 18:13
SOLVED. If you are on a mac, delete the directory ~/Library/Jupyter (make a backup first, of course). My problem was an old kernel definition laying around. Even though I selected the correct env there, Jupyter will also look in that location for parameters.

**Comment by DonJayamanne** [comment] 2017-10-04 16:48
Duplicate of https://github.com/DonJayamanne/vscodeJupyter/issues/33

**Closed by DonJayamanne** 2017-10-04 16:48 UTC

**Comment by kanikachopra20** [comment] 2017-11-17 04:28
I solved this issue by executing following commands on the integrated terminal
python -m pip install --upgrade pip
python -m pip install jupyter

**Comment by ChadWLiu** [comment] 2017-11-29 11:49
Yeah, install Jupyter manually worked for me.
`python3 -m pip install jupyter`

**Comment by hualex** [comment] 2018-03-28 16:23
dont know why but i solve the problem on windows 10 by installing the magicpython extension.
hope it helps for others.

**Comment by jerry-rubikloud** [comment] 2018-04-01 19:28
Nope, this doesn't work if you are using virtualenv. This plugin forces you to install jupyter from outside the virtualenv. It does not respect the environment you choose to use in visual studio code.

**Comment by komorihi** [comment] 2018-04-17 06:40
I got a workaround to select a jupyter kernel on virtualenv on macOS.

1. Activate virtual environment
`$ source env/bin/activate`
2. Start jupyter
`(env) $ jupyter notebook .`
3. Copy the Notebook URL **with token** like this.
`http://localhost:8888/?token=a4fce51b1~~~~~~~~`
3. Execute command below at Command Palette on VSCode.
`Jupyter: Enter the url of local/remote Jupyter Notebook`
4. Paste the Notebook URL **with token**
5. Run cell, and it works!

**Comment by anishmittal2020** [comment] 2018-08-08 23:44
@DonJayamanne I am getting the same error as stated by the OP. Written here:

```log
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command

  ERR spawn jupyter ENOENT: Error: spawn jupyter ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

I am using 
-  Ubuntu 18.04
-  Python 3.6.4 with Anaconda 

I am able to start Jupyter notebook from the Integrated terminal, but the `Run Cell` doesn't start Jupyter notebook and throws the above error.

Please suggest what do I need to do.

**Comment by Shaunakde** [comment] 2018-11-06 06:34
Hey,

I am facing the same issue on version 1.1.4 of the plugin. 

This is the sequence of error messages I get when I try to "Run Cell"

`Unable to determine version of Jupyter, Traceback (most recent call last):
  File "C:\Users\shaun\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\shaun\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\shaun\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\shaun\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\shaun\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\shaun\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\shaun\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\shaun\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

Notebook not selected/started
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command`

**Comment by yashpande** [comment] 2018-11-11 00:16
@Shaunakde I had the same issue but fixed it by opening anaconda prompt and running:

**Comment by yashpande** [comment] 2018-11-11 00:17
@Shaunakde I had the same issue but fixed it by opening anaconda prompt and running:

pip uninstall pyzmq
pip install pyzmq

It seemed to be an issue with anaconda's installation of jupyter and not with the plugin itself.

**Comment by yashpande** [comment] 2018-11-12 20:08
@csheaff Happy to hear that! I was facing other issues after doing this with libraries like numpy not being correctly detected, and ended up doing a full uninstall of anaconda and VS Code then reinstalling anaconda and installing VS code through the anaconda setup wizard. This ended up solving all my issues, so if the pip thing isn't working for anyone they might want to consider doing a reinstall.

**Comment by maPiche** [comment] 2018-11-20 00:51
This solved it for me :

If you click on : view errors -> output -> set drop down menu to Jupiter Notebook

You will see that the port is already in use and it tells you how to open a new token
