### ISSUE TITLE
Jupiter output window won't scroll manually all the way down when many figures present in output

### ISSUE THREAD

**Issue by ajkieloaho** [DonJayamanne/vscodeJupyter#39] opened 2017-04-13 16:24 UTC
### Environment data
VS Code version: 1.11.1
Jupyter Extension version: 1.1.1
OS and version: macOS Sierra

### Logs
Output from ```Jupyter``` output panel
```
<img width="1440" alt="screenshot" src="https://cloud.githubusercontent.com/assets/12850153/25013884/193f5d7c-207e-11e7-994f-31ea435cf26c.png">

```
Output from ```Console window``` (Help->Developer Tools menu)
```
```

### Actual behavior
Jupiter output window won't scroll manually all the way down when many figures present in output. In the screenshot I have scrolled the window as far down as possible and half of the figure and the x-axis stay hidden.  
### Expected  behavior
I want to see x-axis labels.
### Steps to reproduce:
In the screenshot the most important part of the code (producing the figures) to reproduce.

**Comment by DonJayamanne** [comment] 2017-10-04 16:49
Duplicate of https://github.com/DonJayamanne/vscodeJupyter/issues/38

**Closed by DonJayamanne** 2017-10-04 16:49 UTC
