### ISSUE TITLE
Failed to detect jupyter notebook - Windows 10

### ISSUE THREAD

**Issue by chasemohr** [DonJayamanne/vscodeJupyter#72] opened 2017-09-20 22:34 UTC
### Environment data
VS Code version: 1.16.1
Jupyter Extension version: 1.1.3
OS and version: Windows 10 

### Logs
Output from ```Jupyter``` output panel
```
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
```
Output from ```Console window``` (Help->Developer Tools menu)
```

messageService.ts:125 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
e.doShow @ messageService.ts:125
extensionHost.ts:384 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ extensionHost.ts:384
shell.ts:419 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
e.onUnexpectedError @ shell.ts:419
```

### Actual behavior
Cell does not run
### Expected  behavior
Cell should run in VSC - I have a Mac and it doesn't seem to be an issue, but it is on Windows 10 for some reason
### Steps to reproduce:
-

1. Create an new python file in VSC
2. Add the following code:

#%%
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show()

3. Click Run cell
4. Start a new Notebook
![image](https://user-images.githubusercontent.com/18295405/30670886-4dd231fe-9e32-11e7-91b4-6656152233b9.png)

-

**Comment by DonJayamanne** [comment] 2017-10-04 17:00
Duplicate of https://github.com/DonJayamanne/vscodeJupyter/issues/33

**Closed by DonJayamanne** 2017-10-04 17:00 UTC
