### ISSUE TITLE
SVG output from Matlab treated as "Unknown mime type"

### ISSUE THREAD

**Issue by FuriouslyCurious** [DonJayamanne/vscodeJupyter#73] opened 2017-09-21 07:47 UTC
### Environment data
VS Code version: latest
Jupyter Extension version: latest
OS and version: Mac OSX

### Actual behavior
Error message "Unknown Mime type"

### Expected  behavior
Should display a SVG graph

### Steps to reproduce:
```
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

t = np.linspace(0, 20, 500)
plt.plot(t, np.sin(t))
plt.show()

```

**Run Cell**

**Comment by DonJayamanne** [comment] 2017-10-04 16:59
Duplicate of https://github.com/DonJayamanne/vscodeJupyter/issues/47

**Closed by DonJayamanne** 2017-10-04 16:59 UTC
