### ISSUE TITLE
Graphviz graph not drawn

### ISSUE THREAD

**Issue by DrSensor** [DonJayamanne/vscodeJupyter#58] opened 2017-06-22 18:50 UTC
### Environment data
VS Code version: 1.13.1
Jupyter Extension version: 1.1.3
OS and version: Ubuntu 16.04

### Logs
Output from ```Jupyter``` output panel
```
Unknown Mime Type
```
Output from ```Console window``` (Help->Developer Tools menu)
```
extensionHost.ts:293 [Extension Host] clientExists, on server
extensionHost.ts:293 [Extension Host] Object {id: "1498156720022"}id: "1498156720022"__proto__: Object
2webview.ts:91 [Embedded Page] [object Object]
```

### Actual behavior
When running a program/cell in which I produce graphviz dot it doesn't view correctly, but in jupyter notebook it can be rendered.

### Expected  behavior
Produce graph as same as jupyter notebook
![screenshot from 2017-06-23 01-47-57](https://user-images.githubusercontent.com/4953069/27450513-23d1505a-57b6-11e7-81a2-340511ed271c.png)

### Steps to reproduce:
-  Install graphviz
```
pip install graphviz
```

- Use the following code as a cell and run it
```
import graphviz
g = graphviz.Digraph('G')
g.edge('Hello', 'World')
graphviz.Source(g)
```

**Comment by DonJayamanne** [comment] 2017-10-04 17:11
Duplicate of https://github.com/DonJayamanne/vscodeJupyter/issues/47

**Closed by DonJayamanne** 2017-10-04 17:11 UTC
